version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  style_guide = "airbnb"
  environment = ["nodejs"]
  plugins = ["react"]

[[transformers]]
name = "prettier"
enabled = true
